import { StyleSheet } from "react-native";
import { colors } from "../colors";
import {
    baseButton,
    baseSurfaceBorder,
    baseAbsoluteIcon,
    baseSelectItem,
    baseShadow,
    baseCenter,
    baseRowBetween,
} from "./base";

export const stylesComponents = StyleSheet.create({
    buttonPrimary: {
        ...baseButton,
        backgroundColor: colors.primary,
    },
    buttonSecondary: {
        ...baseButton,
        ...baseSurfaceBorder,
    },
    containerLogin: {
        backgroundColor: colors.background,
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        width: '100%',
    },
    containerApp: {
        flex: 1,
        backgroundColor: colors.background,
        padding: 14,
    },
    containerLoginForms: {
        ...baseSurfaceBorder,
        borderRadius: 10,
        padding: 15,
        width: '90%',
    },
    containerForms: {
        ...baseSurfaceBorder,
        borderRadius: 16,
        padding: 20,
        width: '100%',
        alignSelf: 'center',
    },
    textInput: {
        borderColor: colors.border,
        borderWidth: 1,
        borderRadius: 10,
        marginBottom: 15,
        paddingHorizontal: 14,
        paddingVertical: 12,
        width: '100%',
        fontSize: 15,
        color: colors.textPrimary,
    },
    inputWrapper: {
        position: 'relative',
        justifyContent: 'center',
        marginBottom: 15,
    },
    iconOjo: {
        ...baseAbsoluteIcon,
        right: 12,
        justifyContent: 'center',
    },
    inputIconActions: {
        ...baseAbsoluteIcon,
        right: 10,
        flexDirection: 'row',
        gap: 8,
    },
    inputIconBtn: {
        padding: 4,
    },
    selectDropdown: {
        ...baseSurfaceBorder,
        borderRadius: 10,
        marginTop: 4,
        overflow: 'hidden',
    },
    selectItem: {
        ...baseSelectItem,
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
    },
    selectItemLast: {
        ...baseSelectItem,
    },
    selectItemActive: {
        backgroundColor: colors.primarySoft ?? colors.border,
    },
    topBar: {
        ...baseSurfaceBorder,
        width: '100%',
        height: 90,
        justifyContent: 'space-between',
        paddingBottom: 5,
        paddingHorizontal: 20,
        flexDirection: 'row'
    },
    imageProfile: {
        width: 50,
        height: 50,
        borderRadius: 25,
        borderWidth: 2,
        borderColor: colors.border,
    },
    cardOptionContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
        backgroundColor: colors.surface,
    },
    cardOptionIconContainer: {
        width: 48,
        height: 48,
        borderRadius: 24,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    cardOptionTextContainer: {
        flex: 1,
        justifyContent: 'center',
        paddingRight: 8,
    },
    cardProfileContainer: {
        ...baseSurfaceBorder,
        ...baseShadow,
        borderRadius: 12,
        padding: 16,
    },
    cardProfileContent: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    cardProfileAvatar: {
        width: 56,
        height: 56,
        borderRadius: 28,
        backgroundColor: colors.border,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 16,
    },
    cardProfileInfoContainer: {
        flex: 1,
        justifyContent: 'center',
    },
    cardProfileRightContainer: {
        alignItems: 'flex-end',
        justifyContent: 'space-between',
        height: 56,
        marginLeft: 8,
    },
    badge: {
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 12,
        marginBottom: 'auto',
    },
    badgeActive: {
        backgroundColor: colors.successSoft,
    },
    badgeInactive: {
        backgroundColor: colors.errorSoft,
    },
    searchBarContainer: {
        paddingHorizontal: 16,
        paddingTop: 16,
        paddingBottom: 4,
    },
    scrollListContent: {
        padding: 16,
    },
    cardListWrapper: {
        marginBottom: 12,
    },
    fabButton: {
        position: 'absolute',
        bottom: 24,
        right: 24,
        width: 56,
        height: 56,
        borderRadius: 28,
        backgroundColor: colors.primary,
        alignItems: 'center',
        justifyContent: 'center',
        elevation: 6,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
    },
    filterChipContainer: {
        paddingHorizontal: 16,
        paddingBottom: 10,
        gap: 8,
    },
    filterChip: {
        ...baseSurfaceBorder,
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderRadius: 20,
        marginRight: 8,
    },
    filterChipSelected: {
        backgroundColor: colors.primary,
        borderColor: colors.primary,
    },
    cardHomeContainer: {
        ...baseSurfaceBorder,
        flex: 1,
        height: 108,
        borderRadius: 20,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 5,
    },
    bottomBar: {
        backgroundColor: colors.surface,
        borderTopWidth: 1,
        borderTopColor: colors.border,
        flexDirection: 'row',
        justifyContent: 'space-around',
        alignItems: 'center',
        paddingVertical: 6,
        paddingHorizontal: 8,
        width: '100%',
    },
    bottomBarItem: {
        alignItems: 'center',
        justifyContent: 'center',
        flex: 1,
        paddingVertical: 2,
    },
    bottomBarIconContainer: {
        width: 58,
        height: 32,
        borderRadius: 16,
        alignItems: 'center',
        justifyContent: 'center',
    },
    bottomBarIconActive: {
        backgroundColor: colors.primarySoft,
    },
    headerBar: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 16,
        paddingVertical: 14,
        backgroundColor: colors.background,
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
    },
    headerBarActionBtn: {
        padding: 4,
        minWidth: 32,
        alignItems: 'center',
        justifyContent: 'center',
    },
    buttonLogout: {
        ...baseSurfaceBorder,
        borderRadius: 12,
        paddingVertical: 14,
        paddingHorizontal: 16,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
        width: '100%',
    },
    cardEmptyPettyCash: {
        ...baseSurfaceBorder,
        ...baseShadow,
        borderRadius: 18,
        backgroundColor: colors.surface,
        overflow: 'hidden',
        width: '100%',
        alignItems: 'center',
    },
    cardEmptyTopBar: {
        height: 4,
        backgroundColor: colors.primary,
        width: '100%',
    },
    cardEmptyContent: {
        paddingHorizontal: 20,
        paddingVertical: 24,
        alignItems: 'center',
        width: '100%',
    },
    cardEmptyIconContainer: {
        width: 68,
        height: 68,
        borderRadius: 18,
        backgroundColor: colors.primarySoft,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 18,
    },
    cardEmptyButtonWrapper: {
        width: '100%',
        marginTop: 4,
    },
    cardHistoryContainer: {
        ...baseSurfaceBorder,
        ...baseShadow,
        borderRadius: 16,
        padding: 16,
        backgroundColor: colors.surface,
        marginBottom: 12,
        width: '100%',
    },
    cardHistoryHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 6,
    },
    cardHistoryCodeRow: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
        marginRight: 8,
    },
    cardHistoryDateRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        marginBottom: 14,
    },
    cardHistoryMetricsBox: {
        backgroundColor: colors.background,
        borderRadius: 12,
        flexDirection: 'row',
        paddingVertical: 10,
        paddingHorizontal: 6,
        marginBottom: 14,
    },
    cardHistoryMetricCol: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
    },
    cardHistoryMetricDivider: {
        width: 1,
        backgroundColor: colors.border,
        height: '70%',
        alignSelf: 'center',
    },
    cardHistoryFooter: {
        ...baseRowBetween,
    },
    cardHistoryBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 6,
        borderWidth: 1,
        borderColor: colors.border,
        backgroundColor: colors.surface,
    },
    cardPolicyContainer: {
        ...baseSurfaceBorder,
        ...baseShadow,
        borderRadius: 16,
        backgroundColor: colors.surface,
        overflow: 'hidden',
        width: '100%',
        flexDirection: 'row',
        marginBottom: 14,
    },
    cardPolicyLeftBar: {
        width: 5,
        backgroundColor: colors.primary,
    },
    cardPolicyContent: {
        flex: 1,
        flexDirection: 'row',
        paddingHorizontal: 14,
        paddingVertical: 14,
        alignItems: 'flex-start',
    },
    cardPolicyIconContainer: {
        ...baseCenter,
        width: 44,
        height: 44,
        borderRadius: 12,
        backgroundColor: colors.primarySoft,
        marginRight: 12,
    },
    // Reusable Card Elements & Micro-components
    rowBetween: {
        ...baseRowBetween,
    },
    cardInfoCol: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
        marginRight: 8,
    },
    cardAvatarInitials: {
        ...baseCenter,
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: colors.primary,
        marginRight: 12,
    },
    badgePill: {
        flexDirection: 'row',
        alignItems: 'center',
        borderRadius: 16,
        paddingHorizontal: 10,
        paddingVertical: 4,
        gap: 5,
        flexShrink: 0,
    },
    badgeDot: {
        width: 7,
        height: 7,
        borderRadius: 3.5,
    },
    cardMetricsBox: {
        backgroundColor: colors.background,
        borderRadius: 12,
        padding: 14,
        marginBottom: 14,
    },
    progressBarTrack: {
        width: '100%',
        height: 7,
        backgroundColor: colors.border,
        borderRadius: 4,
        marginTop: 12,
        overflow: 'hidden',
    },
    progressBarFill: {
        height: '100%',
        backgroundColor: colors.primary,
        borderRadius: 4,
    },
    chevronButton: {
        ...baseCenter,
        width: 28,
        height: 28,
        borderRadius: 14,
        backgroundColor: colors.background,
    },
    codeBadge: {
        backgroundColor: colors.background,
        borderWidth: 1,
        borderColor: colors.border,
        borderRadius: 8,
        paddingHorizontal: 10,
        paddingVertical: 4,
        flexShrink: 0,
    },
    dividerDashed: {
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
        borderStyle: 'dashed',
        marginVertical: 12,
    },
    // ==========================================
    // EVIDENCIA FOTOGRÁFICA / COMPROBANTES
    // ==========================================
    photoEvidenceCard: {
        ...baseSurfaceBorder,
        borderRadius: 16,
        padding: 20,
        width: '100%',
        marginTop: 16,
    },
    photoEvidenceHeader: {
        ...baseRowBetween,
        marginBottom: 14,
    },
    photoEvidenceTitleContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        flex: 1,
    },
    photoEvidenceBadge: {
        backgroundColor: colors.errorSoft,
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 8,
    },
    photoEvidenceBox: {
        ...baseCenter,
        backgroundColor: '#1E1B2E',
        borderRadius: 16,
        height: 190,
        width: '100%',
        overflow: 'hidden',
        position: 'relative',
    },
    photoEvidencePlaceholder: {
        ...baseCenter,
        width: 58,
        height: 58,
        borderRadius: 16,
        borderWidth: 2,
        borderColor: '#8B5CF6',
        borderStyle: 'dashed',
        backgroundColor: 'rgba(139, 92, 246, 0.12)',
    },
    photoEvidenceActionsBar: {
        position: 'absolute',
        bottom: 12,
        right: 12,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    photoEvidenceChangeBtn: {
        backgroundColor: colors.surface,
        borderWidth: 1.5,
        borderColor: colors.primary,
        borderRadius: 10,
        paddingHorizontal: 14,
        paddingVertical: 8,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
    },
    photoEvidenceTrashBtn: {
        ...baseCenter,
        backgroundColor: colors.surface,
        borderWidth: 1,
        borderColor: colors.border,
        borderRadius: 10,
        paddingHorizontal: 10,
        paddingVertical: 8,
    },
    photoEvidenceFooter: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        gap: 6,
        marginTop: 12,
    },
    photoEvidenceFooterIcon: {
        marginTop: 1,
    },
    // ==========================================
    // BOTONES VARIANTES & FILAS DE SELECTORES
    // ==========================================
    buttonSmall: {
        paddingVertical: 9,
        paddingHorizontal: 8,
        marginBottom: 0,
        gap: 6,
    },
    expenseSourceRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        width: '100%',
        marginBottom: 16,
    },
    flex1: {
        flex: 1,
    },
    buttonDisabled: {
        opacity: 0.45,
    },
    // ==========================================
    // TARJETA DE AUDITORÍA DE GASTO (CardAuditExpense)
    // ==========================================
    cardAuditContainer: {
        backgroundColor: colors.surface,
        borderRadius: 16,
        borderWidth: 1,
        borderColor: colors.border,
        paddingTop: 16,
        paddingBottom: 16,
        paddingRight: 16,
        paddingLeft: 20,
        marginBottom: 16,
        overflow: 'hidden',
        position: 'relative',
        ...baseShadow,
    },
    cardAuditAccentBar: {
        position: 'absolute',
        left: 0,
        top: 0,
        bottom: 0,
        width: 5,
        backgroundColor: colors.primary,
    },
    cardAuditHeaderContainer: {
        marginBottom: 14,
    },
    cardAuditTagsRow: {
        flexDirection: 'row',
        alignItems: 'center',
        flexWrap: 'wrap',
        gap: 10,
    },
    cardAuditCategoryPill: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.background,
        borderWidth: 1,
        borderColor: colors.border,
        borderRadius: 8,
        paddingHorizontal: 10,
        paddingVertical: 5,
        gap: 6,
    },
    cardAuditAmountBox: {
        backgroundColor: colors.background,
        borderRadius: 14,
        paddingHorizontal: 16,
        paddingVertical: 14,
        marginBottom: 14,
        ...baseRowBetween,
    },
    cardAuditAmountBadge: {
        backgroundColor: colors.surface,
        borderWidth: 1,
        borderColor: colors.border,
        borderRadius: 20,
        paddingHorizontal: 12,
        paddingVertical: 7,
    },
    cardAuditEvidenceBox: {
        backgroundColor: colors.background,
        borderWidth: 1,
        borderColor: colors.border,
        borderRadius: 14,
        padding: 12,
        marginBottom: 16,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    cardAuditEvidenceThumb: {
        width: 48,
        height: 48,
        borderRadius: 10,
        backgroundColor: '#1E293B',
        ...baseCenter,
        paddingVertical: 4,
    },
    cardAuditEvidenceAction: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        paddingHorizontal: 6,
        paddingVertical: 4,
    },
    cardAuditActionsRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
    },
    cardAuditBtnReject: {
        flex: 1,
        height: 44,
        backgroundColor: colors.surface,
        borderWidth: 1.5,
        borderColor: colors.error,
        borderRadius: 12,
        ...baseCenter,
        flexDirection: 'row',
        gap: 6,
    },
    cardAuditBtnObserve: {
        flex: 1,
        height: 44,
        backgroundColor: '#FEF9C3',
        borderWidth: 1.5,
        borderColor: '#CA8A04',
        borderRadius: 12,
        ...baseCenter,
        flexDirection: 'row',
        gap: 6,
    },
    cardAuditBtnApprove: {
        flex: 1,
        height: 44,
        backgroundColor: colors.primary,
        borderWidth: 1.5,
        borderColor: colors.primary,
        borderRadius: 12,
        ...baseCenter,
        flexDirection: 'row',
        gap: 6,
    },
    cardAuditStatusBadge: {
        borderRadius: 10,
        paddingVertical: 10,
        paddingHorizontal: 14,
        ...baseCenter,
        flexDirection: 'row',
        gap: 8,
    },
});
